// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the generator file instead!

export interface floatQ {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface doubleQ {
    x: number;
    y: number;
    z: number;
    w: number;
}
