// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the generator file instead!

export interface float2 {
    x: number;
    y: number;
}

export interface float3 {
    x: number;
    y: number;
    z: number;
}

export interface float4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface double2 {
    x: number;
    y: number;
}

export interface double3 {
    x: number;
    y: number;
    z: number;
}

export interface double4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface byte2 {
    x: number;
    y: number;
}

export interface byte3 {
    x: number;
    y: number;
    z: number;
}

export interface byte4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface ushort2 {
    x: number;
    y: number;
}

export interface ushort3 {
    x: number;
    y: number;
    z: number;
}

export interface ushort4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface uint2 {
    x: number;
    y: number;
}

export interface uint3 {
    x: number;
    y: number;
    z: number;
}

export interface uint4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface ulong2 {
    x: number;
    y: number;
}

export interface ulong3 {
    x: number;
    y: number;
    z: number;
}

export interface ulong4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface sbyte2 {
    x: number;
    y: number;
}

export interface sbyte3 {
    x: number;
    y: number;
    z: number;
}

export interface sbyte4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface short2 {
    x: number;
    y: number;
}

export interface short3 {
    x: number;
    y: number;
    z: number;
}

export interface short4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface int2 {
    x: number;
    y: number;
}

export interface int3 {
    x: number;
    y: number;
    z: number;
}

export interface int4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface long2 {
    x: number;
    y: number;
}

export interface long3 {
    x: number;
    y: number;
    z: number;
}

export interface long4 {
    x: number;
    y: number;
    z: number;
    w: number;
}

export interface bool2 {
    x: boolean;
    y: boolean;
}

export interface bool3 {
    x: boolean;
    y: boolean;
    z: boolean;
}

export interface bool4 {
    x: boolean;
    y: boolean;
    z: boolean;
    w: boolean;
}
