import fs from "node:fs";
import path from "path";

const matrixTypes = ["float", "double"];

let output = `// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the ts file instead!\n\n`;

for (const baseType of matrixTypes) {
    for (let dim = 2; dim <= 4; dim++) {
        let rows = [];
        const matrixType = `${baseType}${dim}x${dim}`;
        rows.push(`export interface ${matrixType} {`);
        for (let c = 0; c < dim; c++) {
            for (let r = 0; r < dim; r++) {
                rows.push(`  m${c}${r}: number`);
            }
        }
        rows.push("}");
        output += rows.join("\n") + "\n\n";
    }
}

fs.writeFileSync(path.resolve(__dirname, "../src/models/dataModel/primitives/matrixTypes.ts"), output);
