import fs from "node:fs";
import path from "path";

const nonNullableTypes = new Set(["string", "Uri"]);
const standaloneTypes = [
  "byte",
  "ushort",
  "uint",
  "ulong",

  "sbyte",
  "short",
  "int",
  "long",

  "float",
  "double",

  "decimal",

  "bool",

  "char",
  "string",
  "Uri",

  "color",
  "colorX",
  "color32",
];
const vectorTypes = [
  "float",
  "double",

  "byte",
  "ushort",
  "uint",
  "ulong",

  "sbyte",
  "short",
  "int",
  "long",

  "bool",
];

const quaternionTypes = ["float", "double"];

const matrixTypes = ["float", "double"];

////

const mapType = (type: string) => {
  switch (type) {
    case "string":
    case "Uri":
      return "string";
    case "float":
    case "long":
    case "double":
    case "decimal":
    case "int":
      return "number";
    case "bool":
      return "boolean";
    default:
      return "unknown";
  }
};

const primitiveTypes = [...standaloneTypes];
const transformTypes: { [key: string]: string } = {};
const exportList: { [key: string]: string } = {};

for (let dim = 2; dim <= 4; dim++)
  vectorTypes.forEach((v) => primitiveTypes.push(v + dim));

quaternionTypes.forEach((v) => primitiveTypes.push(v + "Q"));

for (let dim = 2; dim <= 4; dim++)
  matrixTypes.forEach((v) => primitiveTypes.push(`${v}${dim}x${dim}`));

////

let output = `
// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the ts file instead!

import { JsonDerivedType } from "../../utility";
import { Field, SyncArray } from "./";
`;

for (const type of primitiveTypes) {
  output += `
export interface Field_${type} extends Field {
  value: ${transformTypes[type] ?? mapType(type)}
}
`;
  exportList[`Field_${type}`] = type;

  output += `
export interface Array_${type} extends SyncArray {
  values: ${transformTypes[type] ?? mapType(type)}[]
}
`;
  exportList[`Array_${type}`] = type + "[]";

  if (!nonNullableTypes.has(type)) {
    output += `
export interface Field_Nullable_${type} extends Field {
  value?: ${transformTypes[type] ?? mapType(type)}
}
`;
    exportList[`Field_Nullable_${type}`] = type + "?";
  }
}

output += "\n";
output += `export type GeneratedPrimitiveType =
${Object.entries(exportList)
  .map(([k, v]) => "| " + `JsonDerivedType<${k}, "${v}">`)
  .join("\n")}`;

fs.writeFileSync(
  path.resolve(__dirname, "../src/models/dataModel/primitiveContainers.ts"),
  output,
);
