import fs from "node:fs";
import path from "path";

const nonNullableTypes = new Set(["string", "Uri"]);
const standaloneTypes = [
    "byte",
    "ushort",
    "uint",
    "ulong",

    "sbyte",
    "short",
    "int",
    "long",

    "float",
    "double",

    "decimal",

    "bool",

    "char",
    "string",
    "Uri",

    "DateTime",
    "TimeSpan",

    "color",
    "colorX",
    "color32",

    "Rect",
    "IntRect",

    "BoundingBox"
];
const vectorTypes = ["float", "double", "byte", "ushort", "uint", "ulong", "sbyte", "short", "int", "long", "bool"];

const quaternionTypes = ["float", "double"];

const matrixTypes = ["float", "double"];

////

const toTitle = (str: string) => str[0].toUpperCase() + str.slice(1);

const mapType = (type: string) => {
    switch (type) {
        case "string":
        case "Uri":
        case "DateTime":
        case "TimeSpan":
            return "string";
        case "float":
        case "long":
        case "double":
        case "decimal":
        case "int":
        case "byte":
        case "ushort":
        case "uint":
        case "ulong":
        case "sbyte":
        case "short":
        case "char":
            return "number";
        case "bool":
            return "boolean";
        default:
            return type;
    }
};

const primitiveTypes = [...standaloneTypes];
const transformTypes: { [key: string]: string } = {};
const importList: { [key: string]: string } = {};

for (let dim = 2; dim <= 4; dim++) vectorTypes.forEach((v) => primitiveTypes.push(v + dim));

quaternionTypes.forEach((v) => primitiveTypes.push(v + "Q"));

for (let dim = 2; dim <= 4; dim++) matrixTypes.forEach((v) => primitiveTypes.push(`${v}${dim}x${dim}`));

////

let output = `
// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the generator file instead!
`;

let functions = ``;

for (const type of primitiveTypes) {
    functions += `
export const create${toTitle(type)} = (value: ${transformTypes[type] ?? mapType(type)}): OmitIdentity<Field_${type}> => ({
    $type: "${type}",
    value: value
})
`;
    importList[`Field_${type}`] = type;

    functions += `
export const create${toTitle(type)}Array = (values: ${transformTypes[type] ?? mapType(type)}[]): OmitIdentity<Array_${type}> => ({
    $type: "${type + "[]"}",
    values: values
})
`;
    importList[`Array_${type}`] = type + "[]";

    if (!nonNullableTypes.has(type)) {
        functions += `
export const createNullable${toTitle(type)} = (value?: ${transformTypes[type] ?? mapType(type)}): OmitIdentity<Field_Nullable_${type}> => ({
    $type: "${type + "?"}",
    value: value
})
`;
        importList[`Field_Nullable_${type}`] = type + "?";
    }
}

output += `\nimport type { OmitIdentity } from "@/utility/index.js";`;
output += `\nimport type { ${[...primitiveTypes.filter((x) => x == mapType(x) && x !== "number" && x !== "string"), ...Object.keys(importList)].join(", ")} } from "@/models/index.js";`;
output += `\n${functions}\n`;

fs.writeFileSync(path.resolve(__dirname, "../src/client/builders/primitiveBuilder.ts"), output);
