import fs from "node:fs";
import path from "path";

const quaternionTypes = ["float", "double"];
const letters = ["x", "y", "z", "w"];

let output = `// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the ts file instead!\n\n`;

for (const baseType of quaternionTypes) {
  let rows = [];
  const quatType = `${baseType}Q`;
  rows.push(`export interface ${quatType} {`);
  for (let n = 0; n < 4; n++) {
    rows.push(`  ${letters[n]}: number`);
  }
  rows.push("}");
  output += rows.join("\n") + "\n\n";
}

fs.writeFileSync(
  path.resolve(__dirname, "../src/models/dataModel/primitives/quaternions.ts"),
  output,
);
