import fs from "node:fs";
import path from "path";

const vectorTypes = ["float", "double", "byte", "ushort", "uint", "ulong", "sbyte", "short", "int", "long", "bool"];
const letters = ["x", "y", "z", "w"];

const mapType = (type: string) => {
    switch (type) {
        case "bool":
            return "boolean";
        default:
            return "number";
    }
};

let output = `// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the generator file instead!\n\n`;

for (const baseType of vectorTypes) {
    for (let dim = 2; dim <= 4; dim++) {
        let rows = [];
        const vectorType = baseType + dim;
        rows.push(`export interface ${vectorType} {`);
        for (let n = 0; n < dim; n++) {
            rows.push(`  ${letters[n]}: ${mapType(baseType)}`);
        }
        rows.push("}");
        output += rows.join("\n") + "\n\n";
    }
}

fs.writeFileSync(path.resolve(__dirname, "../src/models/dataModel/primitives/vectors.ts"), output);
