// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the generator file instead!

import type {
    color,
    colorX,
    color32,
    Rect,
    IntRect,
    BoundingBox,
    float2,
    double2,
    byte2,
    ushort2,
    uint2,
    ulong2,
    sbyte2,
    short2,
    int2,
    long2,
    bool2,
    float3,
    double3,
    byte3,
    ushort3,
    uint3,
    ulong3,
    sbyte3,
    short3,
    int3,
    long3,
    bool3,
    float4,
    double4,
    byte4,
    ushort4,
    uint4,
    ulong4,
    sbyte4,
    short4,
    int4,
    long4,
    bool4,
    floatQ,
    doubleQ,
    float2x2,
    double2x2,
    float3x3,
    double3x3,
    float4x4,
    double4x4,
    Field_byte,
    Array_byte,
    Field_Nullable_byte,
    Field_ushort,
    Array_ushort,
    Field_Nullable_ushort,
    Field_uint,
    Array_uint,
    Field_Nullable_uint,
    Field_ulong,
    Array_ulong,
    Field_Nullable_ulong,
    Field_sbyte,
    Array_sbyte,
    Field_Nullable_sbyte,
    Field_short,
    Array_short,
    Field_Nullable_short,
    Field_int,
    Array_int,
    Field_Nullable_int,
    Field_long,
    Array_long,
    Field_Nullable_long,
    Field_float,
    Array_float,
    Field_Nullable_float,
    Field_double,
    Array_double,
    Field_Nullable_double,
    Field_decimal,
    Array_decimal,
    Field_Nullable_decimal,
    Field_bool,
    Array_bool,
    Field_Nullable_bool,
    Field_char,
    Array_char,
    Field_Nullable_char,
    Field_string,
    Array_string,
    Field_Uri,
    Array_Uri,
    Field_DateTime,
    Array_DateTime,
    Field_Nullable_DateTime,
    Field_TimeSpan,
    Array_TimeSpan,
    Field_Nullable_TimeSpan,
    Field_color,
    Array_color,
    Field_Nullable_color,
    Field_colorX,
    Array_colorX,
    Field_Nullable_colorX,
    Field_color32,
    Array_color32,
    Field_Nullable_color32,
    Field_Rect,
    Array_Rect,
    Field_Nullable_Rect,
    Field_IntRect,
    Array_IntRect,
    Field_Nullable_IntRect,
    Field_BoundingBox,
    Array_BoundingBox,
    Field_Nullable_BoundingBox,
    Field_float2,
    Array_float2,
    Field_Nullable_float2,
    Field_double2,
    Array_double2,
    Field_Nullable_double2,
    Field_byte2,
    Array_byte2,
    Field_Nullable_byte2,
    Field_ushort2,
    Array_ushort2,
    Field_Nullable_ushort2,
    Field_uint2,
    Array_uint2,
    Field_Nullable_uint2,
    Field_ulong2,
    Array_ulong2,
    Field_Nullable_ulong2,
    Field_sbyte2,
    Array_sbyte2,
    Field_Nullable_sbyte2,
    Field_short2,
    Array_short2,
    Field_Nullable_short2,
    Field_int2,
    Array_int2,
    Field_Nullable_int2,
    Field_long2,
    Array_long2,
    Field_Nullable_long2,
    Field_bool2,
    Array_bool2,
    Field_Nullable_bool2,
    Field_float3,
    Array_float3,
    Field_Nullable_float3,
    Field_double3,
    Array_double3,
    Field_Nullable_double3,
    Field_byte3,
    Array_byte3,
    Field_Nullable_byte3,
    Field_ushort3,
    Array_ushort3,
    Field_Nullable_ushort3,
    Field_uint3,
    Array_uint3,
    Field_Nullable_uint3,
    Field_ulong3,
    Array_ulong3,
    Field_Nullable_ulong3,
    Field_sbyte3,
    Array_sbyte3,
    Field_Nullable_sbyte3,
    Field_short3,
    Array_short3,
    Field_Nullable_short3,
    Field_int3,
    Array_int3,
    Field_Nullable_int3,
    Field_long3,
    Array_long3,
    Field_Nullable_long3,
    Field_bool3,
    Array_bool3,
    Field_Nullable_bool3,
    Field_float4,
    Array_float4,
    Field_Nullable_float4,
    Field_double4,
    Array_double4,
    Field_Nullable_double4,
    Field_byte4,
    Array_byte4,
    Field_Nullable_byte4,
    Field_ushort4,
    Array_ushort4,
    Field_Nullable_ushort4,
    Field_uint4,
    Array_uint4,
    Field_Nullable_uint4,
    Field_ulong4,
    Array_ulong4,
    Field_Nullable_ulong4,
    Field_sbyte4,
    Array_sbyte4,
    Field_Nullable_sbyte4,
    Field_short4,
    Array_short4,
    Field_Nullable_short4,
    Field_int4,
    Array_int4,
    Field_Nullable_int4,
    Field_long4,
    Array_long4,
    Field_Nullable_long4,
    Field_bool4,
    Array_bool4,
    Field_Nullable_bool4,
    Field_floatQ,
    Array_floatQ,
    Field_Nullable_floatQ,
    Field_doubleQ,
    Array_doubleQ,
    Field_Nullable_doubleQ,
    Field_float2x2,
    Array_float2x2,
    Field_Nullable_float2x2,
    Field_double2x2,
    Array_double2x2,
    Field_Nullable_double2x2,
    Field_float3x3,
    Array_float3x3,
    Field_Nullable_float3x3,
    Field_double3x3,
    Array_double3x3,
    Field_Nullable_double3x3,
    Field_float4x4,
    Array_float4x4,
    Field_Nullable_float4x4,
    Field_double4x4,
    Array_double4x4,
    Field_Nullable_double4x4
} from "@/models/index.js";

export const createByte = (value: number): Field_byte => ({
    $type: "byte",
    value: value
});

export const createByteArray = (values: number[]): Array_byte => ({
    $type: "byte[]",
    values: values
});

export const createNullableByte = (value?: number): Field_Nullable_byte => ({
    $type: "byte?",
    value: value
});

export const createUshort = (value: number): Field_ushort => ({
    $type: "ushort",
    value: value
});

export const createUshortArray = (values: number[]): Array_ushort => ({
    $type: "ushort[]",
    values: values
});

export const createNullableUshort = (value?: number): Field_Nullable_ushort => ({
    $type: "ushort?",
    value: value
});

export const createUint = (value: number): Field_uint => ({
    $type: "uint",
    value: value
});

export const createUintArray = (values: number[]): Array_uint => ({
    $type: "uint[]",
    values: values
});

export const createNullableUint = (value?: number): Field_Nullable_uint => ({
    $type: "uint?",
    value: value
});

export const createUlong = (value: number): Field_ulong => ({
    $type: "ulong",
    value: value
});

export const createUlongArray = (values: number[]): Array_ulong => ({
    $type: "ulong[]",
    values: values
});

export const createNullableUlong = (value?: number): Field_Nullable_ulong => ({
    $type: "ulong?",
    value: value
});

export const createSbyte = (value: number): Field_sbyte => ({
    $type: "sbyte",
    value: value
});

export const createSbyteArray = (values: number[]): Array_sbyte => ({
    $type: "sbyte[]",
    values: values
});

export const createNullableSbyte = (value?: number): Field_Nullable_sbyte => ({
    $type: "sbyte?",
    value: value
});

export const createShort = (value: number): Field_short => ({
    $type: "short",
    value: value
});

export const createShortArray = (values: number[]): Array_short => ({
    $type: "short[]",
    values: values
});

export const createNullableShort = (value?: number): Field_Nullable_short => ({
    $type: "short?",
    value: value
});

export const createInt = (value: number): Field_int => ({
    $type: "int",
    value: value
});

export const createIntArray = (values: number[]): Array_int => ({
    $type: "int[]",
    values: values
});

export const createNullableInt = (value?: number): Field_Nullable_int => ({
    $type: "int?",
    value: value
});

export const createLong = (value: number): Field_long => ({
    $type: "long",
    value: value
});

export const createLongArray = (values: number[]): Array_long => ({
    $type: "long[]",
    values: values
});

export const createNullableLong = (value?: number): Field_Nullable_long => ({
    $type: "long?",
    value: value
});

export const createFloat = (value: number): Field_float => ({
    $type: "float",
    value: value
});

export const createFloatArray = (values: number[]): Array_float => ({
    $type: "float[]",
    values: values
});

export const createNullableFloat = (value?: number): Field_Nullable_float => ({
    $type: "float?",
    value: value
});

export const createDouble = (value: number): Field_double => ({
    $type: "double",
    value: value
});

export const createDoubleArray = (values: number[]): Array_double => ({
    $type: "double[]",
    values: values
});

export const createNullableDouble = (value?: number): Field_Nullable_double => ({
    $type: "double?",
    value: value
});

export const createDecimal = (value: number): Field_decimal => ({
    $type: "decimal",
    value: value
});

export const createDecimalArray = (values: number[]): Array_decimal => ({
    $type: "decimal[]",
    values: values
});

export const createNullableDecimal = (value?: number): Field_Nullable_decimal => ({
    $type: "decimal?",
    value: value
});

export const createBool = (value: boolean): Field_bool => ({
    $type: "bool",
    value: value
});

export const createBoolArray = (values: boolean[]): Array_bool => ({
    $type: "bool[]",
    values: values
});

export const createNullableBool = (value?: boolean): Field_Nullable_bool => ({
    $type: "bool?",
    value: value
});

export const createChar = (value: number): Field_char => ({
    $type: "char",
    value: value
});

export const createCharArray = (values: number[]): Array_char => ({
    $type: "char[]",
    values: values
});

export const createNullableChar = (value?: number): Field_Nullable_char => ({
    $type: "char?",
    value: value
});

export const createString = (value: string): Field_string => ({
    $type: "string",
    value: value
});

export const createStringArray = (values: string[]): Array_string => ({
    $type: "string[]",
    values: values
});

export const createUri = (value: string): Field_Uri => ({
    $type: "Uri",
    value: value
});

export const createUriArray = (values: string[]): Array_Uri => ({
    $type: "Uri[]",
    values: values
});

export const createDateTime = (value: string): Field_DateTime => ({
    $type: "DateTime",
    value: value
});

export const createDateTimeArray = (values: string[]): Array_DateTime => ({
    $type: "DateTime[]",
    values: values
});

export const createNullableDateTime = (value?: string): Field_Nullable_DateTime => ({
    $type: "DateTime?",
    value: value
});

export const createTimeSpan = (value: string): Field_TimeSpan => ({
    $type: "TimeSpan",
    value: value
});

export const createTimeSpanArray = (values: string[]): Array_TimeSpan => ({
    $type: "TimeSpan[]",
    values: values
});

export const createNullableTimeSpan = (value?: string): Field_Nullable_TimeSpan => ({
    $type: "TimeSpan?",
    value: value
});

export const createColor = (value: color): Field_color => ({
    $type: "color",
    value: value
});

export const createColorArray = (values: color[]): Array_color => ({
    $type: "color[]",
    values: values
});

export const createNullableColor = (value?: color): Field_Nullable_color => ({
    $type: "color?",
    value: value
});

export const createColorX = (value: colorX): Field_colorX => ({
    $type: "colorX",
    value: value
});

export const createColorXArray = (values: colorX[]): Array_colorX => ({
    $type: "colorX[]",
    values: values
});

export const createNullableColorX = (value?: colorX): Field_Nullable_colorX => ({
    $type: "colorX?",
    value: value
});

export const createColor32 = (value: color32): Field_color32 => ({
    $type: "color32",
    value: value
});

export const createColor32Array = (values: color32[]): Array_color32 => ({
    $type: "color32[]",
    values: values
});

export const createNullableColor32 = (value?: color32): Field_Nullable_color32 => ({
    $type: "color32?",
    value: value
});

export const createRect = (value: Rect): Field_Rect => ({
    $type: "Rect",
    value: value
});

export const createRectArray = (values: Rect[]): Array_Rect => ({
    $type: "Rect[]",
    values: values
});

export const createNullableRect = (value?: Rect): Field_Nullable_Rect => ({
    $type: "Rect?",
    value: value
});

export const createIntRect = (value: IntRect): Field_IntRect => ({
    $type: "IntRect",
    value: value
});

export const createIntRectArray = (values: IntRect[]): Array_IntRect => ({
    $type: "IntRect[]",
    values: values
});

export const createNullableIntRect = (value?: IntRect): Field_Nullable_IntRect => ({
    $type: "IntRect?",
    value: value
});

export const createBoundingBox = (value: BoundingBox): Field_BoundingBox => ({
    $type: "BoundingBox",
    value: value
});

export const createBoundingBoxArray = (values: BoundingBox[]): Array_BoundingBox => ({
    $type: "BoundingBox[]",
    values: values
});

export const createNullableBoundingBox = (value?: BoundingBox): Field_Nullable_BoundingBox => ({
    $type: "BoundingBox?",
    value: value
});

export const createFloat2 = (value: float2): Field_float2 => ({
    $type: "float2",
    value: value
});

export const createFloat2Array = (values: float2[]): Array_float2 => ({
    $type: "float2[]",
    values: values
});

export const createNullableFloat2 = (value?: float2): Field_Nullable_float2 => ({
    $type: "float2?",
    value: value
});

export const createDouble2 = (value: double2): Field_double2 => ({
    $type: "double2",
    value: value
});

export const createDouble2Array = (values: double2[]): Array_double2 => ({
    $type: "double2[]",
    values: values
});

export const createNullableDouble2 = (value?: double2): Field_Nullable_double2 => ({
    $type: "double2?",
    value: value
});

export const createByte2 = (value: byte2): Field_byte2 => ({
    $type: "byte2",
    value: value
});

export const createByte2Array = (values: byte2[]): Array_byte2 => ({
    $type: "byte2[]",
    values: values
});

export const createNullableByte2 = (value?: byte2): Field_Nullable_byte2 => ({
    $type: "byte2?",
    value: value
});

export const createUshort2 = (value: ushort2): Field_ushort2 => ({
    $type: "ushort2",
    value: value
});

export const createUshort2Array = (values: ushort2[]): Array_ushort2 => ({
    $type: "ushort2[]",
    values: values
});

export const createNullableUshort2 = (value?: ushort2): Field_Nullable_ushort2 => ({
    $type: "ushort2?",
    value: value
});

export const createUint2 = (value: uint2): Field_uint2 => ({
    $type: "uint2",
    value: value
});

export const createUint2Array = (values: uint2[]): Array_uint2 => ({
    $type: "uint2[]",
    values: values
});

export const createNullableUint2 = (value?: uint2): Field_Nullable_uint2 => ({
    $type: "uint2?",
    value: value
});

export const createUlong2 = (value: ulong2): Field_ulong2 => ({
    $type: "ulong2",
    value: value
});

export const createUlong2Array = (values: ulong2[]): Array_ulong2 => ({
    $type: "ulong2[]",
    values: values
});

export const createNullableUlong2 = (value?: ulong2): Field_Nullable_ulong2 => ({
    $type: "ulong2?",
    value: value
});

export const createSbyte2 = (value: sbyte2): Field_sbyte2 => ({
    $type: "sbyte2",
    value: value
});

export const createSbyte2Array = (values: sbyte2[]): Array_sbyte2 => ({
    $type: "sbyte2[]",
    values: values
});

export const createNullableSbyte2 = (value?: sbyte2): Field_Nullable_sbyte2 => ({
    $type: "sbyte2?",
    value: value
});

export const createShort2 = (value: short2): Field_short2 => ({
    $type: "short2",
    value: value
});

export const createShort2Array = (values: short2[]): Array_short2 => ({
    $type: "short2[]",
    values: values
});

export const createNullableShort2 = (value?: short2): Field_Nullable_short2 => ({
    $type: "short2?",
    value: value
});

export const createInt2 = (value: int2): Field_int2 => ({
    $type: "int2",
    value: value
});

export const createInt2Array = (values: int2[]): Array_int2 => ({
    $type: "int2[]",
    values: values
});

export const createNullableInt2 = (value?: int2): Field_Nullable_int2 => ({
    $type: "int2?",
    value: value
});

export const createLong2 = (value: long2): Field_long2 => ({
    $type: "long2",
    value: value
});

export const createLong2Array = (values: long2[]): Array_long2 => ({
    $type: "long2[]",
    values: values
});

export const createNullableLong2 = (value?: long2): Field_Nullable_long2 => ({
    $type: "long2?",
    value: value
});

export const createBool2 = (value: bool2): Field_bool2 => ({
    $type: "bool2",
    value: value
});

export const createBool2Array = (values: bool2[]): Array_bool2 => ({
    $type: "bool2[]",
    values: values
});

export const createNullableBool2 = (value?: bool2): Field_Nullable_bool2 => ({
    $type: "bool2?",
    value: value
});

export const createFloat3 = (value: float3): Field_float3 => ({
    $type: "float3",
    value: value
});

export const createFloat3Array = (values: float3[]): Array_float3 => ({
    $type: "float3[]",
    values: values
});

export const createNullableFloat3 = (value?: float3): Field_Nullable_float3 => ({
    $type: "float3?",
    value: value
});

export const createDouble3 = (value: double3): Field_double3 => ({
    $type: "double3",
    value: value
});

export const createDouble3Array = (values: double3[]): Array_double3 => ({
    $type: "double3[]",
    values: values
});

export const createNullableDouble3 = (value?: double3): Field_Nullable_double3 => ({
    $type: "double3?",
    value: value
});

export const createByte3 = (value: byte3): Field_byte3 => ({
    $type: "byte3",
    value: value
});

export const createByte3Array = (values: byte3[]): Array_byte3 => ({
    $type: "byte3[]",
    values: values
});

export const createNullableByte3 = (value?: byte3): Field_Nullable_byte3 => ({
    $type: "byte3?",
    value: value
});

export const createUshort3 = (value: ushort3): Field_ushort3 => ({
    $type: "ushort3",
    value: value
});

export const createUshort3Array = (values: ushort3[]): Array_ushort3 => ({
    $type: "ushort3[]",
    values: values
});

export const createNullableUshort3 = (value?: ushort3): Field_Nullable_ushort3 => ({
    $type: "ushort3?",
    value: value
});

export const createUint3 = (value: uint3): Field_uint3 => ({
    $type: "uint3",
    value: value
});

export const createUint3Array = (values: uint3[]): Array_uint3 => ({
    $type: "uint3[]",
    values: values
});

export const createNullableUint3 = (value?: uint3): Field_Nullable_uint3 => ({
    $type: "uint3?",
    value: value
});

export const createUlong3 = (value: ulong3): Field_ulong3 => ({
    $type: "ulong3",
    value: value
});

export const createUlong3Array = (values: ulong3[]): Array_ulong3 => ({
    $type: "ulong3[]",
    values: values
});

export const createNullableUlong3 = (value?: ulong3): Field_Nullable_ulong3 => ({
    $type: "ulong3?",
    value: value
});

export const createSbyte3 = (value: sbyte3): Field_sbyte3 => ({
    $type: "sbyte3",
    value: value
});

export const createSbyte3Array = (values: sbyte3[]): Array_sbyte3 => ({
    $type: "sbyte3[]",
    values: values
});

export const createNullableSbyte3 = (value?: sbyte3): Field_Nullable_sbyte3 => ({
    $type: "sbyte3?",
    value: value
});

export const createShort3 = (value: short3): Field_short3 => ({
    $type: "short3",
    value: value
});

export const createShort3Array = (values: short3[]): Array_short3 => ({
    $type: "short3[]",
    values: values
});

export const createNullableShort3 = (value?: short3): Field_Nullable_short3 => ({
    $type: "short3?",
    value: value
});

export const createInt3 = (value: int3): Field_int3 => ({
    $type: "int3",
    value: value
});

export const createInt3Array = (values: int3[]): Array_int3 => ({
    $type: "int3[]",
    values: values
});

export const createNullableInt3 = (value?: int3): Field_Nullable_int3 => ({
    $type: "int3?",
    value: value
});

export const createLong3 = (value: long3): Field_long3 => ({
    $type: "long3",
    value: value
});

export const createLong3Array = (values: long3[]): Array_long3 => ({
    $type: "long3[]",
    values: values
});

export const createNullableLong3 = (value?: long3): Field_Nullable_long3 => ({
    $type: "long3?",
    value: value
});

export const createBool3 = (value: bool3): Field_bool3 => ({
    $type: "bool3",
    value: value
});

export const createBool3Array = (values: bool3[]): Array_bool3 => ({
    $type: "bool3[]",
    values: values
});

export const createNullableBool3 = (value?: bool3): Field_Nullable_bool3 => ({
    $type: "bool3?",
    value: value
});

export const createFloat4 = (value: float4): Field_float4 => ({
    $type: "float4",
    value: value
});

export const createFloat4Array = (values: float4[]): Array_float4 => ({
    $type: "float4[]",
    values: values
});

export const createNullableFloat4 = (value?: float4): Field_Nullable_float4 => ({
    $type: "float4?",
    value: value
});

export const createDouble4 = (value: double4): Field_double4 => ({
    $type: "double4",
    value: value
});

export const createDouble4Array = (values: double4[]): Array_double4 => ({
    $type: "double4[]",
    values: values
});

export const createNullableDouble4 = (value?: double4): Field_Nullable_double4 => ({
    $type: "double4?",
    value: value
});

export const createByte4 = (value: byte4): Field_byte4 => ({
    $type: "byte4",
    value: value
});

export const createByte4Array = (values: byte4[]): Array_byte4 => ({
    $type: "byte4[]",
    values: values
});

export const createNullableByte4 = (value?: byte4): Field_Nullable_byte4 => ({
    $type: "byte4?",
    value: value
});

export const createUshort4 = (value: ushort4): Field_ushort4 => ({
    $type: "ushort4",
    value: value
});

export const createUshort4Array = (values: ushort4[]): Array_ushort4 => ({
    $type: "ushort4[]",
    values: values
});

export const createNullableUshort4 = (value?: ushort4): Field_Nullable_ushort4 => ({
    $type: "ushort4?",
    value: value
});

export const createUint4 = (value: uint4): Field_uint4 => ({
    $type: "uint4",
    value: value
});

export const createUint4Array = (values: uint4[]): Array_uint4 => ({
    $type: "uint4[]",
    values: values
});

export const createNullableUint4 = (value?: uint4): Field_Nullable_uint4 => ({
    $type: "uint4?",
    value: value
});

export const createUlong4 = (value: ulong4): Field_ulong4 => ({
    $type: "ulong4",
    value: value
});

export const createUlong4Array = (values: ulong4[]): Array_ulong4 => ({
    $type: "ulong4[]",
    values: values
});

export const createNullableUlong4 = (value?: ulong4): Field_Nullable_ulong4 => ({
    $type: "ulong4?",
    value: value
});

export const createSbyte4 = (value: sbyte4): Field_sbyte4 => ({
    $type: "sbyte4",
    value: value
});

export const createSbyte4Array = (values: sbyte4[]): Array_sbyte4 => ({
    $type: "sbyte4[]",
    values: values
});

export const createNullableSbyte4 = (value?: sbyte4): Field_Nullable_sbyte4 => ({
    $type: "sbyte4?",
    value: value
});

export const createShort4 = (value: short4): Field_short4 => ({
    $type: "short4",
    value: value
});

export const createShort4Array = (values: short4[]): Array_short4 => ({
    $type: "short4[]",
    values: values
});

export const createNullableShort4 = (value?: short4): Field_Nullable_short4 => ({
    $type: "short4?",
    value: value
});

export const createInt4 = (value: int4): Field_int4 => ({
    $type: "int4",
    value: value
});

export const createInt4Array = (values: int4[]): Array_int4 => ({
    $type: "int4[]",
    values: values
});

export const createNullableInt4 = (value?: int4): Field_Nullable_int4 => ({
    $type: "int4?",
    value: value
});

export const createLong4 = (value: long4): Field_long4 => ({
    $type: "long4",
    value: value
});

export const createLong4Array = (values: long4[]): Array_long4 => ({
    $type: "long4[]",
    values: values
});

export const createNullableLong4 = (value?: long4): Field_Nullable_long4 => ({
    $type: "long4?",
    value: value
});

export const createBool4 = (value: bool4): Field_bool4 => ({
    $type: "bool4",
    value: value
});

export const createBool4Array = (values: bool4[]): Array_bool4 => ({
    $type: "bool4[]",
    values: values
});

export const createNullableBool4 = (value?: bool4): Field_Nullable_bool4 => ({
    $type: "bool4?",
    value: value
});

export const createFloatQ = (value: floatQ): Field_floatQ => ({
    $type: "floatQ",
    value: value
});

export const createFloatQArray = (values: floatQ[]): Array_floatQ => ({
    $type: "floatQ[]",
    values: values
});

export const createNullableFloatQ = (value?: floatQ): Field_Nullable_floatQ => ({
    $type: "floatQ?",
    value: value
});

export const createDoubleQ = (value: doubleQ): Field_doubleQ => ({
    $type: "doubleQ",
    value: value
});

export const createDoubleQArray = (values: doubleQ[]): Array_doubleQ => ({
    $type: "doubleQ[]",
    values: values
});

export const createNullableDoubleQ = (value?: doubleQ): Field_Nullable_doubleQ => ({
    $type: "doubleQ?",
    value: value
});

export const createFloat2x2 = (value: float2x2): Field_float2x2 => ({
    $type: "float2x2",
    value: value
});

export const createFloat2x2Array = (values: float2x2[]): Array_float2x2 => ({
    $type: "float2x2[]",
    values: values
});

export const createNullableFloat2x2 = (value?: float2x2): Field_Nullable_float2x2 => ({
    $type: "float2x2?",
    value: value
});

export const createDouble2x2 = (value: double2x2): Field_double2x2 => ({
    $type: "double2x2",
    value: value
});

export const createDouble2x2Array = (values: double2x2[]): Array_double2x2 => ({
    $type: "double2x2[]",
    values: values
});

export const createNullableDouble2x2 = (value?: double2x2): Field_Nullable_double2x2 => ({
    $type: "double2x2?",
    value: value
});

export const createFloat3x3 = (value: float3x3): Field_float3x3 => ({
    $type: "float3x3",
    value: value
});

export const createFloat3x3Array = (values: float3x3[]): Array_float3x3 => ({
    $type: "float3x3[]",
    values: values
});

export const createNullableFloat3x3 = (value?: float3x3): Field_Nullable_float3x3 => ({
    $type: "float3x3?",
    value: value
});

export const createDouble3x3 = (value: double3x3): Field_double3x3 => ({
    $type: "double3x3",
    value: value
});

export const createDouble3x3Array = (values: double3x3[]): Array_double3x3 => ({
    $type: "double3x3[]",
    values: values
});

export const createNullableDouble3x3 = (value?: double3x3): Field_Nullable_double3x3 => ({
    $type: "double3x3?",
    value: value
});

export const createFloat4x4 = (value: float4x4): Field_float4x4 => ({
    $type: "float4x4",
    value: value
});

export const createFloat4x4Array = (values: float4x4[]): Array_float4x4 => ({
    $type: "float4x4[]",
    values: values
});

export const createNullableFloat4x4 = (value?: float4x4): Field_Nullable_float4x4 => ({
    $type: "float4x4?",
    value: value
});

export const createDouble4x4 = (value: double4x4): Field_double4x4 => ({
    $type: "double4x4",
    value: value
});

export const createDouble4x4Array = (values: double4x4[]): Array_double4x4 => ({
    $type: "double4x4[]",
    values: values
});

export const createNullableDouble4x4 = (value?: double4x4): Field_Nullable_double4x4 => ({
    $type: "double4x4?",
    value: value
});
