// AUTOGENERATED!!! Do not modify! Your changes will be lost after regenerating from the ts file.
// Modify the ts file instead!

import { JsonDerivedType } from "../../utility";
import { Field, SyncArray } from "./";

export interface Field_byte extends Field {
  value: unknown;
}

export interface Array_byte extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_byte extends Field {
  value?: unknown;
}

export interface Field_ushort extends Field {
  value: unknown;
}

export interface Array_ushort extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ushort extends Field {
  value?: unknown;
}

export interface Field_uint extends Field {
  value: unknown;
}

export interface Array_uint extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_uint extends Field {
  value?: unknown;
}

export interface Field_ulong extends Field {
  value: unknown;
}

export interface Array_ulong extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ulong extends Field {
  value?: unknown;
}

export interface Field_sbyte extends Field {
  value: unknown;
}

export interface Array_sbyte extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_sbyte extends Field {
  value?: unknown;
}

export interface Field_short extends Field {
  value: unknown;
}

export interface Array_short extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_short extends Field {
  value?: unknown;
}

export interface Field_int extends Field {
  value: number;
}

export interface Array_int extends SyncArray {
  values: number[];
}

export interface Field_Nullable_int extends Field {
  value?: number;
}

export interface Field_long extends Field {
  value: number;
}

export interface Array_long extends SyncArray {
  values: number[];
}

export interface Field_Nullable_long extends Field {
  value?: number;
}

export interface Field_float extends Field {
  value: number;
}

export interface Array_float extends SyncArray {
  values: number[];
}

export interface Field_Nullable_float extends Field {
  value?: number;
}

export interface Field_double extends Field {
  value: number;
}

export interface Array_double extends SyncArray {
  values: number[];
}

export interface Field_Nullable_double extends Field {
  value?: number;
}

export interface Field_decimal extends Field {
  value: number;
}

export interface Array_decimal extends SyncArray {
  values: number[];
}

export interface Field_Nullable_decimal extends Field {
  value?: number;
}

export interface Field_bool extends Field {
  value: boolean;
}

export interface Array_bool extends SyncArray {
  values: boolean[];
}

export interface Field_Nullable_bool extends Field {
  value?: boolean;
}

export interface Field_char extends Field {
  value: unknown;
}

export interface Array_char extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_char extends Field {
  value?: unknown;
}

export interface Field_string extends Field {
  value: string;
}

export interface Array_string extends SyncArray {
  values: string[];
}

export interface Field_Uri extends Field {
  value: string;
}

export interface Array_Uri extends SyncArray {
  values: string[];
}

export interface Field_color extends Field {
  value: unknown;
}

export interface Array_color extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_color extends Field {
  value?: unknown;
}

export interface Field_colorX extends Field {
  value: unknown;
}

export interface Array_colorX extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_colorX extends Field {
  value?: unknown;
}

export interface Field_color32 extends Field {
  value: unknown;
}

export interface Array_color32 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_color32 extends Field {
  value?: unknown;
}

export interface Field_float2 extends Field {
  value: unknown;
}

export interface Array_float2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_float2 extends Field {
  value?: unknown;
}

export interface Field_double2 extends Field {
  value: unknown;
}

export interface Array_double2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_double2 extends Field {
  value?: unknown;
}

export interface Field_byte2 extends Field {
  value: unknown;
}

export interface Array_byte2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_byte2 extends Field {
  value?: unknown;
}

export interface Field_ushort2 extends Field {
  value: unknown;
}

export interface Array_ushort2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ushort2 extends Field {
  value?: unknown;
}

export interface Field_uint2 extends Field {
  value: unknown;
}

export interface Array_uint2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_uint2 extends Field {
  value?: unknown;
}

export interface Field_ulong2 extends Field {
  value: unknown;
}

export interface Array_ulong2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ulong2 extends Field {
  value?: unknown;
}

export interface Field_sbyte2 extends Field {
  value: unknown;
}

export interface Array_sbyte2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_sbyte2 extends Field {
  value?: unknown;
}

export interface Field_short2 extends Field {
  value: unknown;
}

export interface Array_short2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_short2 extends Field {
  value?: unknown;
}

export interface Field_int2 extends Field {
  value: unknown;
}

export interface Array_int2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_int2 extends Field {
  value?: unknown;
}

export interface Field_long2 extends Field {
  value: unknown;
}

export interface Array_long2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_long2 extends Field {
  value?: unknown;
}

export interface Field_bool2 extends Field {
  value: unknown;
}

export interface Array_bool2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_bool2 extends Field {
  value?: unknown;
}

export interface Field_float3 extends Field {
  value: unknown;
}

export interface Array_float3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_float3 extends Field {
  value?: unknown;
}

export interface Field_double3 extends Field {
  value: unknown;
}

export interface Array_double3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_double3 extends Field {
  value?: unknown;
}

export interface Field_byte3 extends Field {
  value: unknown;
}

export interface Array_byte3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_byte3 extends Field {
  value?: unknown;
}

export interface Field_ushort3 extends Field {
  value: unknown;
}

export interface Array_ushort3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ushort3 extends Field {
  value?: unknown;
}

export interface Field_uint3 extends Field {
  value: unknown;
}

export interface Array_uint3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_uint3 extends Field {
  value?: unknown;
}

export interface Field_ulong3 extends Field {
  value: unknown;
}

export interface Array_ulong3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ulong3 extends Field {
  value?: unknown;
}

export interface Field_sbyte3 extends Field {
  value: unknown;
}

export interface Array_sbyte3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_sbyte3 extends Field {
  value?: unknown;
}

export interface Field_short3 extends Field {
  value: unknown;
}

export interface Array_short3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_short3 extends Field {
  value?: unknown;
}

export interface Field_int3 extends Field {
  value: unknown;
}

export interface Array_int3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_int3 extends Field {
  value?: unknown;
}

export interface Field_long3 extends Field {
  value: unknown;
}

export interface Array_long3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_long3 extends Field {
  value?: unknown;
}

export interface Field_bool3 extends Field {
  value: unknown;
}

export interface Array_bool3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_bool3 extends Field {
  value?: unknown;
}

export interface Field_float4 extends Field {
  value: unknown;
}

export interface Array_float4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_float4 extends Field {
  value?: unknown;
}

export interface Field_double4 extends Field {
  value: unknown;
}

export interface Array_double4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_double4 extends Field {
  value?: unknown;
}

export interface Field_byte4 extends Field {
  value: unknown;
}

export interface Array_byte4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_byte4 extends Field {
  value?: unknown;
}

export interface Field_ushort4 extends Field {
  value: unknown;
}

export interface Array_ushort4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ushort4 extends Field {
  value?: unknown;
}

export interface Field_uint4 extends Field {
  value: unknown;
}

export interface Array_uint4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_uint4 extends Field {
  value?: unknown;
}

export interface Field_ulong4 extends Field {
  value: unknown;
}

export interface Array_ulong4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_ulong4 extends Field {
  value?: unknown;
}

export interface Field_sbyte4 extends Field {
  value: unknown;
}

export interface Array_sbyte4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_sbyte4 extends Field {
  value?: unknown;
}

export interface Field_short4 extends Field {
  value: unknown;
}

export interface Array_short4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_short4 extends Field {
  value?: unknown;
}

export interface Field_int4 extends Field {
  value: unknown;
}

export interface Array_int4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_int4 extends Field {
  value?: unknown;
}

export interface Field_long4 extends Field {
  value: unknown;
}

export interface Array_long4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_long4 extends Field {
  value?: unknown;
}

export interface Field_bool4 extends Field {
  value: unknown;
}

export interface Array_bool4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_bool4 extends Field {
  value?: unknown;
}

export interface Field_floatQ extends Field {
  value: unknown;
}

export interface Array_floatQ extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_floatQ extends Field {
  value?: unknown;
}

export interface Field_doubleQ extends Field {
  value: unknown;
}

export interface Array_doubleQ extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_doubleQ extends Field {
  value?: unknown;
}

export interface Field_float2x2 extends Field {
  value: unknown;
}

export interface Array_float2x2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_float2x2 extends Field {
  value?: unknown;
}

export interface Field_double2x2 extends Field {
  value: unknown;
}

export interface Array_double2x2 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_double2x2 extends Field {
  value?: unknown;
}

export interface Field_float3x3 extends Field {
  value: unknown;
}

export interface Array_float3x3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_float3x3 extends Field {
  value?: unknown;
}

export interface Field_double3x3 extends Field {
  value: unknown;
}

export interface Array_double3x3 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_double3x3 extends Field {
  value?: unknown;
}

export interface Field_float4x4 extends Field {
  value: unknown;
}

export interface Array_float4x4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_float4x4 extends Field {
  value?: unknown;
}

export interface Field_double4x4 extends Field {
  value: unknown;
}

export interface Array_double4x4 extends SyncArray {
  values: unknown[];
}

export interface Field_Nullable_double4x4 extends Field {
  value?: unknown;
}

export type GeneratedPrimitiveType =
  | JsonDerivedType<Field_byte, "byte">
  | JsonDerivedType<Array_byte, "byte[]">
  | JsonDerivedType<Field_Nullable_byte, "byte?">
  | JsonDerivedType<Field_ushort, "ushort">
  | JsonDerivedType<Array_ushort, "ushort[]">
  | JsonDerivedType<Field_Nullable_ushort, "ushort?">
  | JsonDerivedType<Field_uint, "uint">
  | JsonDerivedType<Array_uint, "uint[]">
  | JsonDerivedType<Field_Nullable_uint, "uint?">
  | JsonDerivedType<Field_ulong, "ulong">
  | JsonDerivedType<Array_ulong, "ulong[]">
  | JsonDerivedType<Field_Nullable_ulong, "ulong?">
  | JsonDerivedType<Field_sbyte, "sbyte">
  | JsonDerivedType<Array_sbyte, "sbyte[]">
  | JsonDerivedType<Field_Nullable_sbyte, "sbyte?">
  | JsonDerivedType<Field_short, "short">
  | JsonDerivedType<Array_short, "short[]">
  | JsonDerivedType<Field_Nullable_short, "short?">
  | JsonDerivedType<Field_int, "int">
  | JsonDerivedType<Array_int, "int[]">
  | JsonDerivedType<Field_Nullable_int, "int?">
  | JsonDerivedType<Field_long, "long">
  | JsonDerivedType<Array_long, "long[]">
  | JsonDerivedType<Field_Nullable_long, "long?">
  | JsonDerivedType<Field_float, "float">
  | JsonDerivedType<Array_float, "float[]">
  | JsonDerivedType<Field_Nullable_float, "float?">
  | JsonDerivedType<Field_double, "double">
  | JsonDerivedType<Array_double, "double[]">
  | JsonDerivedType<Field_Nullable_double, "double?">
  | JsonDerivedType<Field_decimal, "decimal">
  | JsonDerivedType<Array_decimal, "decimal[]">
  | JsonDerivedType<Field_Nullable_decimal, "decimal?">
  | JsonDerivedType<Field_bool, "bool">
  | JsonDerivedType<Array_bool, "bool[]">
  | JsonDerivedType<Field_Nullable_bool, "bool?">
  | JsonDerivedType<Field_char, "char">
  | JsonDerivedType<Array_char, "char[]">
  | JsonDerivedType<Field_Nullable_char, "char?">
  | JsonDerivedType<Field_string, "string">
  | JsonDerivedType<Array_string, "string[]">
  | JsonDerivedType<Field_Uri, "Uri">
  | JsonDerivedType<Array_Uri, "Uri[]">
  | JsonDerivedType<Field_color, "color">
  | JsonDerivedType<Array_color, "color[]">
  | JsonDerivedType<Field_Nullable_color, "color?">
  | JsonDerivedType<Field_colorX, "colorX">
  | JsonDerivedType<Array_colorX, "colorX[]">
  | JsonDerivedType<Field_Nullable_colorX, "colorX?">
  | JsonDerivedType<Field_color32, "color32">
  | JsonDerivedType<Array_color32, "color32[]">
  | JsonDerivedType<Field_Nullable_color32, "color32?">
  | JsonDerivedType<Field_float2, "float2">
  | JsonDerivedType<Array_float2, "float2[]">
  | JsonDerivedType<Field_Nullable_float2, "float2?">
  | JsonDerivedType<Field_double2, "double2">
  | JsonDerivedType<Array_double2, "double2[]">
  | JsonDerivedType<Field_Nullable_double2, "double2?">
  | JsonDerivedType<Field_byte2, "byte2">
  | JsonDerivedType<Array_byte2, "byte2[]">
  | JsonDerivedType<Field_Nullable_byte2, "byte2?">
  | JsonDerivedType<Field_ushort2, "ushort2">
  | JsonDerivedType<Array_ushort2, "ushort2[]">
  | JsonDerivedType<Field_Nullable_ushort2, "ushort2?">
  | JsonDerivedType<Field_uint2, "uint2">
  | JsonDerivedType<Array_uint2, "uint2[]">
  | JsonDerivedType<Field_Nullable_uint2, "uint2?">
  | JsonDerivedType<Field_ulong2, "ulong2">
  | JsonDerivedType<Array_ulong2, "ulong2[]">
  | JsonDerivedType<Field_Nullable_ulong2, "ulong2?">
  | JsonDerivedType<Field_sbyte2, "sbyte2">
  | JsonDerivedType<Array_sbyte2, "sbyte2[]">
  | JsonDerivedType<Field_Nullable_sbyte2, "sbyte2?">
  | JsonDerivedType<Field_short2, "short2">
  | JsonDerivedType<Array_short2, "short2[]">
  | JsonDerivedType<Field_Nullable_short2, "short2?">
  | JsonDerivedType<Field_int2, "int2">
  | JsonDerivedType<Array_int2, "int2[]">
  | JsonDerivedType<Field_Nullable_int2, "int2?">
  | JsonDerivedType<Field_long2, "long2">
  | JsonDerivedType<Array_long2, "long2[]">
  | JsonDerivedType<Field_Nullable_long2, "long2?">
  | JsonDerivedType<Field_bool2, "bool2">
  | JsonDerivedType<Array_bool2, "bool2[]">
  | JsonDerivedType<Field_Nullable_bool2, "bool2?">
  | JsonDerivedType<Field_float3, "float3">
  | JsonDerivedType<Array_float3, "float3[]">
  | JsonDerivedType<Field_Nullable_float3, "float3?">
  | JsonDerivedType<Field_double3, "double3">
  | JsonDerivedType<Array_double3, "double3[]">
  | JsonDerivedType<Field_Nullable_double3, "double3?">
  | JsonDerivedType<Field_byte3, "byte3">
  | JsonDerivedType<Array_byte3, "byte3[]">
  | JsonDerivedType<Field_Nullable_byte3, "byte3?">
  | JsonDerivedType<Field_ushort3, "ushort3">
  | JsonDerivedType<Array_ushort3, "ushort3[]">
  | JsonDerivedType<Field_Nullable_ushort3, "ushort3?">
  | JsonDerivedType<Field_uint3, "uint3">
  | JsonDerivedType<Array_uint3, "uint3[]">
  | JsonDerivedType<Field_Nullable_uint3, "uint3?">
  | JsonDerivedType<Field_ulong3, "ulong3">
  | JsonDerivedType<Array_ulong3, "ulong3[]">
  | JsonDerivedType<Field_Nullable_ulong3, "ulong3?">
  | JsonDerivedType<Field_sbyte3, "sbyte3">
  | JsonDerivedType<Array_sbyte3, "sbyte3[]">
  | JsonDerivedType<Field_Nullable_sbyte3, "sbyte3?">
  | JsonDerivedType<Field_short3, "short3">
  | JsonDerivedType<Array_short3, "short3[]">
  | JsonDerivedType<Field_Nullable_short3, "short3?">
  | JsonDerivedType<Field_int3, "int3">
  | JsonDerivedType<Array_int3, "int3[]">
  | JsonDerivedType<Field_Nullable_int3, "int3?">
  | JsonDerivedType<Field_long3, "long3">
  | JsonDerivedType<Array_long3, "long3[]">
  | JsonDerivedType<Field_Nullable_long3, "long3?">
  | JsonDerivedType<Field_bool3, "bool3">
  | JsonDerivedType<Array_bool3, "bool3[]">
  | JsonDerivedType<Field_Nullable_bool3, "bool3?">
  | JsonDerivedType<Field_float4, "float4">
  | JsonDerivedType<Array_float4, "float4[]">
  | JsonDerivedType<Field_Nullable_float4, "float4?">
  | JsonDerivedType<Field_double4, "double4">
  | JsonDerivedType<Array_double4, "double4[]">
  | JsonDerivedType<Field_Nullable_double4, "double4?">
  | JsonDerivedType<Field_byte4, "byte4">
  | JsonDerivedType<Array_byte4, "byte4[]">
  | JsonDerivedType<Field_Nullable_byte4, "byte4?">
  | JsonDerivedType<Field_ushort4, "ushort4">
  | JsonDerivedType<Array_ushort4, "ushort4[]">
  | JsonDerivedType<Field_Nullable_ushort4, "ushort4?">
  | JsonDerivedType<Field_uint4, "uint4">
  | JsonDerivedType<Array_uint4, "uint4[]">
  | JsonDerivedType<Field_Nullable_uint4, "uint4?">
  | JsonDerivedType<Field_ulong4, "ulong4">
  | JsonDerivedType<Array_ulong4, "ulong4[]">
  | JsonDerivedType<Field_Nullable_ulong4, "ulong4?">
  | JsonDerivedType<Field_sbyte4, "sbyte4">
  | JsonDerivedType<Array_sbyte4, "sbyte4[]">
  | JsonDerivedType<Field_Nullable_sbyte4, "sbyte4?">
  | JsonDerivedType<Field_short4, "short4">
  | JsonDerivedType<Array_short4, "short4[]">
  | JsonDerivedType<Field_Nullable_short4, "short4?">
  | JsonDerivedType<Field_int4, "int4">
  | JsonDerivedType<Array_int4, "int4[]">
  | JsonDerivedType<Field_Nullable_int4, "int4?">
  | JsonDerivedType<Field_long4, "long4">
  | JsonDerivedType<Array_long4, "long4[]">
  | JsonDerivedType<Field_Nullable_long4, "long4?">
  | JsonDerivedType<Field_bool4, "bool4">
  | JsonDerivedType<Array_bool4, "bool4[]">
  | JsonDerivedType<Field_Nullable_bool4, "bool4?">
  | JsonDerivedType<Field_floatQ, "floatQ">
  | JsonDerivedType<Array_floatQ, "floatQ[]">
  | JsonDerivedType<Field_Nullable_floatQ, "floatQ?">
  | JsonDerivedType<Field_doubleQ, "doubleQ">
  | JsonDerivedType<Array_doubleQ, "doubleQ[]">
  | JsonDerivedType<Field_Nullable_doubleQ, "doubleQ?">
  | JsonDerivedType<Field_float2x2, "float2x2">
  | JsonDerivedType<Array_float2x2, "float2x2[]">
  | JsonDerivedType<Field_Nullable_float2x2, "float2x2?">
  | JsonDerivedType<Field_double2x2, "double2x2">
  | JsonDerivedType<Array_double2x2, "double2x2[]">
  | JsonDerivedType<Field_Nullable_double2x2, "double2x2?">
  | JsonDerivedType<Field_float3x3, "float3x3">
  | JsonDerivedType<Array_float3x3, "float3x3[]">
  | JsonDerivedType<Field_Nullable_float3x3, "float3x3?">
  | JsonDerivedType<Field_double3x3, "double3x3">
  | JsonDerivedType<Array_double3x3, "double3x3[]">
  | JsonDerivedType<Field_Nullable_double3x3, "double3x3?">
  | JsonDerivedType<Field_float4x4, "float4x4">
  | JsonDerivedType<Array_float4x4, "float4x4[]">
  | JsonDerivedType<Field_Nullable_float4x4, "float4x4?">
  | JsonDerivedType<Field_double4x4, "double4x4">
  | JsonDerivedType<Array_double4x4, "double4x4[]">
  | JsonDerivedType<Field_Nullable_double4x4, "double4x4?">;
